check-coverage: true
per-file: true
lines: 100
statements: 100
functions: 100
branches: 100
watermarks:
  lines:
    - 100
    - 100
  functions:
    - 100
    - 100
  branches:
    - 100
    - 100
  statements:
    - 100
    - 100
reporter:
  - html
  - text
report-dir: ./coverage
produce-source-map: true
preserve-comments: false
cache: false
